### ISSUE TITLE
[Bug] Dot is too big in landscape mode

### ISSUE THREAD

**Issue by Glitchy-Tozier** [thetwom/Tuner#12] opened 2021-06-29 20:16 UTC
Pictures are pretty self-explanatory, I think:
![Screenshot_20210629-195620_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123861594-a9c2cd00-d927-11eb-85ce-e2e64911c3c2.jpg)
![20210629_221517.jpg](https://user-images.githubusercontent.com/59611881/123861605-ac252700-d927-11eb-9ba1-a12c7ccbe9b5.jpg)

**Comment by thetwom** [comment] 2021-06-30 05:52
actually the dot is not made to fit inbetween the 5cent lines, but as far as I recall its dependent on the text size. So its size depends also on your phone settings. I would prefer not to couple the size to the 5cent lines, since coupling stuff also makes work harder in future (one extra issue you have to make sure not to break :-). E.g. what if the 5c lines are increased to a 10c limit since this is really good enough? Should the dot grow? What if we make the limit smaller? Is the dot now becoming to small? 
But I understand that on your screen it looks like it should fit inbetween since its size almost fits ...

**Comment by Glitchy-Tozier** [comment] 2021-06-30 06:08
I don't think this is my phone's fault.

In normal, vertical mode the dot fits perfectly.
![20210630_080533.jpg](https://user-images.githubusercontent.com/59611881/123910033-2d0d0e80-d97a-11eb-93d2-31fb6382b3a3.jpg)
![20210630_080612.jpg](https://user-images.githubusercontent.com/59611881/123910039-2ed6d200-d97a-11eb-995a-fc242245f848.jpg)

It is only in horizontal mode that it is too large (see original screenshots), and I doubt that my phone changes font-sizes when its being rotated.

**Comment by thetwom** [comment] 2021-06-30 06:12
no, its not the font size that changes, its the distance of the 5c line that changes. Meaning that depending on plot size the 5c lines are further apart of closer ... Since I don't scale the dot with the plot size it somtimes fits inbetween the lines and sometimes not. For most plots this is the expected behavior: Symbols and line widths should not be dependent on the size since otherwise the will either become too small or weirdly thick.

**Comment by Glitchy-Tozier** [comment] 2021-06-30 18:04
But the purpose of the dot is to fit right between those lines, isn't it?

**Comment by thetwom** [comment] 2021-07-01 05:26
no, the purpose of the dot is to mark the head of the line. It is not connected to the 5c lines. That it fits in your portrait mode is indeed a coincidence. Phones with other screen/font sizes will yield different results.

**Comment by Glitchy-Tozier** [comment] 2021-07-01 06:07
Interesting, i see.
Personally, i think it would look great if the dot always filled out the two lines perfectly, but if you don't like that change, we can close this issue now :)

**Comment by thetwom** [comment] 2021-07-01 06:24
I understand, that such this detail in theory would be nice. But since it really depend on many factors, when it is helpful and when not (as said, phone format is a factor but there are also others like the ranges of the plot, the 5c-tolerance, the plot layout, ...), I think the most consistent solution is to have it independent. So I will close this issue. Still, thanks a lot for the suggestions.

**Closed by thetwom** 2021-07-01 06:24 UTC
