### ISSUE TITLE
The app stops working after changing Hz

### ISSUE THREAD

**Issue by opExe** [thetwom/Tuner#75] opened 2024-01-05 13:39 UTC
Is anyone else experiencing this?

**Steps to reproduce:**
1. Tap on the frequency change button in the lower left corner.
2. Enter any frequency.
3. Tap **Done**.
4. The app stops listening and must be restarted.

**Comment by thetwom** [comment] 2024-01-05 14:31
Thanks for the report. I cannot reproduce the issue here. A few questions:

- Could you provide the android version you are using?
- If you change the frequency inside the settings, will things work as expected?
- Will the "listening" also stop, if you abort instead of pressing done?
- Will you have the same problem if you change the temperament (the button in the bottom center)?

**Comment by opExe** [comment] 2024-01-05 18:49
Thank you for your response. Here are the answers:
* Android 11
* If I make the change inside the settings, everything works as expected.
* The listening will not stop if I abort.
* Yes, the same problem actually arises when I change the temperament.

The problem appears every other time I change the frequency/temperament. Thus, when the app stops listening and I change the frequency/temperament again, it starts working. Similarily, if I temporarily open the settings and then go back, it starts working.

By "stop listening" I mean that the app behaves as if no sound is played. I have tried to reinstall and reset the app, but it did not solve the problem.

I did now try the app on another phone (Android 12), and could not reproduce the problem there. That suggests that the problem lies with my phone.

**Comment by thetwom** [comment] 2024-01-06 15:48
Thanks for the detailed information. I will see if I can track down the issue, however it might be difficult without being able to reproduce it here. Are you used to get logging information (logcat) from apps? In case I don't find the issue, it might help to install an specially prepared version and check the logging info.

**Comment by thetwom** [comment] 2024-01-06 21:16
One further question: Can you try the behaviour in the scientific mode (go to settings and switch on scientific mode). Does the tuner stop listening completely when changing the reference frequency, or do the spectrum and autocorrelation plots show results, while the plot history stops?

**Comment by opExe** [comment] 2024-01-06 23:25
> Are you used to get logging information (logcat) from apps?

I haven't done it before, but I could certainly try.

> Can you try the behaviour in the scientific mode (go to settings and switch on scientific mode). Does the tuner stop listening completely when changing the reference frequency, or do the spectrum and autocorrelation plots show results, while the plot history stops?

The spectrum and autocorrelation plots, as well as the plot history, "freeze" at their latest positions.

**Comment by thetwom** [comment] 2024-01-07 21:58
Thanks for the further answers. It is not clear to me yet, why this happens. It is indeed the case, that the "listening" is restarted, when changing such settings. I don't find any obvious issues, but I created a test version, which should handle this more safely: [v6.6.0-rc2](https://github.com/thetwom/Tuner/releases/tag/v6.6.0-rc2). Maybe you can test it? 

Please note that this version is not signed with the keys from fdroid or google play but with my own keys. So you would have to uninstall before installing the new version. 

Up to now logcat infos are not needed. If the test version doesn't fix the issue, I would have to instrument a version, which would hopefully point us closer to the issue. Thanks for willing for trying to provide such infos.

**Comment by opExe** [comment] 2024-01-09 18:22
Thank you for the test version. I installed it, and **the issue was gone**! Just as a reference, I uninstalled it and installed the app from Google Play again, and that version still contains the issue. So, whatever you did to solve the problem, it worked! I'll be waiting for the updated version in Google Play.

Thank you for your assistance and for providing the best tuning and metronome apps I have ever used! Feel free to close this issue now, unless you need any more information from me.

**Comment by thetwom** [comment] 2024-01-09 19:43
Thanks a lot for testing.  Your explanations helped to track down the problem very closely to its source. Seems as it was enough, to solve the problem. I am still a bit puzzled, what really caused the issue, but I think it is not worth doing too much research on this at the moment. Good to know that the problem is reproducible on your phone. That gives hope, that it won't appear again :-). 

I will release an updated version in the next days. I am trying do some improvements on one other issue and would wait until this is done. Shouldn't be too long ...

**Comment by thetwom** [comment] 2024-01-10 20:06
I released now [v6.6.0](https://github.com/thetwom/Tuner/releases/tag/v6.6.0). Should appear on google play and fdroid within the next days. 

I will close this issue in the next days, when the release is everywhere available.

Thanks again for the report and the help.

**Comment by opExe** [comment] 2024-01-12 07:35
Great! I can confirm that the app on Google Play now works flawlessly.

**Comment by thetwom** [comment] 2024-01-12 21:21
Thanks again, closing this issue now.

**Closed by thetwom** 2024-01-12 21:21 UTC
