### ISSUE TITLE
Green point starts at random location

### ISSUE THREAD

**Issue by Glitchy-Tozier** [thetwom/Tuner#14] opened 2021-06-30 06:02 UTC
No idea why but i feel like this could be improved. 
- Maybe hide it until there really is a sound
- M aybe give it some fake trail.
- Maybe make it remember the last trail drawn.

![Screenshot_20210630-073514_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123909536-7a3cb080-d979-11eb-8b31-9621c66a2afb.jpg)

**Comment by thetwom** [comment] 2021-06-30 06:04
this indeed looks odd. Will have a look.

**Comment by thetwom** [comment] 2021-07-05 05:23
I had a look. If I understand the your situation correctly, the behavior is indeed intended.
- The first frequency, which is found will be accepted in the pitch history/Tonverlauf
- We don't necessarily accept the next frequency in the pitch history/Tonverlauf. It is only accepted if it is close enough to the first frequency. This avoids the diagram from jumping around wildly if the pitch is not very clear.
- We only jump to a new frequency if there were several values close to the new frequency (Anzahl Werte um neuen Ton zu akzeptieren). So, e.g. if there is just a single outlier, it will be ignored. 

In your example, I guess, the following happened:
- First frequency is around dsharp5. 
- Next frequency is way off (50Hz, which is not nearly dsharp5). So we wait if there more frequencies around 49Hz before we accept it.

So, it's not really a random position. It could of course be worth a thought to only evaluate frequency above a certain level of loudness (so it won't show "random" start positions). Will have to check if the loudness can be reliably evaluated on a smartphone ...

**Comment by Glitchy-Tozier** [comment] 2021-07-05 08:22
> It could of course be worth a thought to only evaluate frequency above a certain level of loudness

A few other options i can think of that might be worth trying:
- Alsways place the dot on `A` (440 Hz or whatever the user has set)
- Don't display the dot at all until a proper frequency is found and start with the view zoomed in on `A`
- Don't display the dot at all until a proper frequency is found and start with the view zoomed out all the way.

**Comment by thetwom** [comment] 2021-07-05 09:12
the problem is, that the first position of the dot IS a proper position. It's indeed the first frequency which was found. It still might not make sense since it is found based on background noise ... so the question is not about an incorrectly positioned green dot, but about  detecting if a found frequency is a "proper" frequency.

**Comment by Glitchy-Tozier** [comment] 2021-07-05 18:52
I understand what you're saying, but I don't think it makes sense from a users perspective.

I think those are our best options:
- Don't draw the dot until a normal signal exists (the kind of signal that would result in the line being drawn)
- Remember where the dot was in the previous app-usage and use its last position.

**Comment by thetwom** [comment] 2022-10-02 20:28
Closing this, since the dot actually does not start at a random location. It could appear like it since it is not clear how to take a low signal apart from no signal. Still thanks for reporting.

**Closed by thetwom** 2022-10-02 20:28 UTC
