### ISSUE TITLE
Back button does not close the app

### ISSUE THREAD

**Issue by josealberto4444** [thetwom/Tuner#32] opened 2022-10-06 11:29 UTC
Hi, since last update (5.1.0), pressing the back button while in the main window of the app does not do anything. It used to close the app. Is it intentional? I cannot find a way to close the app different to switching it to background and then swiping it.

Thanks for the app, it helps me with my music studies. ^^

**Comment by thetwom** [comment] 2022-10-06 14:13
Thanks for reporting the issue. I indeed had to adapt some logic here in order stay compatible with the latest android developments. In this process, I missed that the app won't close anymore. Will be fixed in the next version.

**Comment by thetwom** [comment] 2022-10-27 06:39
Sorry, I lost a bit track of releasing the latest changes. I now created a release candidate, where the behavior is enabled again:
 [v5.2.0-rc1](https://github.com/thetwom/Tuner/releases/tag/v5.2.0-rc1). I am planning to make this official within the next days.

**Comment by thetwom** [comment] 2022-10-31 08:59
Now official with [v5.2.0](https://github.com/thetwom/Tuner/releases/tag/v5.2.0). Thanks again for reporting the issue!

**Closed by thetwom** 2022-10-31 08:59 UTC

**Comment by josealberto4444** [comment] 2022-10-31 09:05
Thank you for fixing it and for the fantastic app! ^^

**Comment by lindoman** [comment] 2023-01-28 15:37
For me (running Android 12 on  LineageOS) the issue is still a problem. A couple of other apps I use ask me to tap the "back" button twice to exit. is that a possibility?

**Comment by josealberto4444** [comment] 2023-01-28 17:24
I'm using version 5.3.0 of this app in Lineage 20.0 (Android 13) and the issue is solved. I also tested it in Lineage 18.1 (Android 11) and it also gets closed when pushing the back button, but I don't have any phone with Lineage 19 (Android 12) to test.

When you say it's not solved, you mean that there is no way to close the app with the back button or that you'd prefer to close it tapping twice?

**Comment by lindoman** [comment] 2023-01-28 18:18
Apologies, I was  mistaken, I was distracted by the notification of use of the microphone, which for some reason stayed on for some time after the application lost focus.

**Comment by thetwom** [comment] 2023-01-28 21:22
Is the microphone notification staying on for long? The app should stop recording audio as soon as it is in the background ...

**Comment by lindoman** [comment] 2023-01-28 21:25
> Is the microphone notification staying on for long? The app should stop recording audio as soon as it is in the background ...
No, I got myself confused with another app also using the microphone. Only about 2 seconds in normal operation

**Comment by thetwom** [comment] 2023-01-28 21:35
Ok, good. Thanks for the feedback!
